//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Core.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Core.Templates.CoreTemplates", typeof(CoreTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;||Header||&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        table {
        ///            border-spacing: 0;
        ///            border-collapse: collapse;
        ///        }
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: text-top;
        ///            text-align: justify;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailTemplate {
            get {
                return ResourceManager.GetString("EmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Error Recorded&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-family: Arial, Verd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ErrorTemplate {
            get {
                return ResourceManager.GetString("ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Generic Template&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: text-top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-family: Aria [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GenericTemplate {
            get {
                return ResourceManager.GetString("GenericTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Error Recorded&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-family: Arial, Verd [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NoAccessTemplate {
            get {
                return ResourceManager.GetString("NoAccessTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Generic Report Template&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: text-top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-famil [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ReportTemplate {
            get {
                return ResourceManager.GetString("ReportTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Error Recorded&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: text-top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-family: Arial, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ServiceTemplate {
            get {
                return ResourceManager.GetString("ServiceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Welcome To ||System||&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        td {
        ///            font-family: Arial, Verdana;
        ///            font-size: 12px;
        ///            border: 1px solid;
        ///            border-color: darkslategrey;
        ///            vertical-align: top;
        ///            text-align: left;
        ///            padding: 2px;
        ///            margin: 0;
        ///        }
        ///        p {
        ///            font-family: Aria [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeTemplate {
            get {
                return ResourceManager.GetString("WelcomeTemplate", resourceCulture);
            }
        }
    }
}
